name: facturapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  open_file: ^3.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/vaca.png"
  adaptative_icon_background: "assets/vaca.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#333333"
  image: assets/splash.png
  android: true
  ios: true
